### ISSUE TITLE
Miner

### ISSUE THREAD

**Issue by iliashenko** [forknote/dashcoin#5]
Hello! Huston, i have a little problem:
Fatal: Specify --address option
Address is DSH, what is Options?

**Comment by pmitchev** [comment]
What command are you using?

**Comment by iliashenko** [comment]
/Applications/Cryptocoins/Wallets/dashcoin-mac/miner D7HnHoPCYhj4L73HVXbtyjFhZmATA1F4V6f7TYKWge8GXARfPc5Lwj3JR2nFSML1N5HNX1PgZ7D4zcCmYTf4SMyV5BcLcHb

**Comment by pmitchev** [comment]
you need to specify --address and --daemon-rpc-port .
See --help for more info
